version: 2.1
jobs:
  build:
    working_directory: .
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: docker build -t app .

workflows:
  version: 2
  build_image:
    jobs:
      - build:
          filters:
            branches:
             only: main
